version: '3'
services: 
    scm:
        build: "./backend-scm"
        ports:
            - "3030:3030"
    user:
        build: "./backend-user"
        ports: 
            - "3020:3020"
    frontend:
        build: "./frontend"
        ports:
            - "80:80"