apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
      - name: backend-scm
        image: backend-scm:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3030
